
#include "EXT_INTERRUPT.h"

void INTERRUPT_ENABLE()
{

#if GLOBAL_ENTERRUPT_STATUS == ENABLE_GLOBAL_INTERRUPT
	SET_BIT(SREG,7);
#elif  GLOBAL_ENTERRUPT_STATUS == DISABLE_GLOBAL_INTERRUPT
	CLR_BIT(SREG,7);
#endif

}

void EXT_INT0_INIT()
{
	SET_BIT(GICR,EXTERNAL_INTERRUPT_0);
#if EXT_INT0_STATUS == EXTERNAL_INT0_LOW_LEVEL
	CLR_BIT(MCUCR,0);
	CLR_BIT(MCUCR,1);

#elif EXT_INT0_STATUS == EXTERNAL_INT0_ANY_CHANGE
	SET_BIT(MCUCR,0);
	CLR_BIT(MCUCR,1);

#elif EXT_INT0_STATUS == EXTERNAL_INT0_FALLING_EDGE
	CLR_BIT(MCUCR,0);
	SET_BIT(MCUCR,1);


#elif EXT_INT0_STATUS == EXTERNAL_INT0_RISING_EDGE
	SET_BIT(MCUCR,0);
	SET_BIT(MCUCR,1);

#endif

}

void EXT_INT1_INIT()
{
	SET_BIT(GICR,EXTERNAL_INTERRUPT_1);
#if EXT_INT1_STATUS == EXTERNAL_INT1_LOW_LEVEL
	CLR_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);

#elif EXT_INT1_STATUS == EXTERNAL_INT1_ANY_CHANGE
	SET_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);

#elif EXT_INT1_STATUS == EXTERNAL_INT1_FALLING_EDGE
	CLR_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);


#elif EXT_INT1_STATUS == EXTERNAL_INT1_RISING_EDGE
	SET_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);

#endif

}

void EXT_INT2_INIT()
{
	SET_BIT(GICR,EXTERNAL_INTERRUPT_2);
#if EXT_INT2_STATUS == EXTERNAL_INT2_FALLING_EDGE
	CLR_BIT(MCUSCR,6);



#elif EXT_INT2_STATUS == EXTERNAL_INT2_RISING_EDGE
	SET_BIT(MCUSCR,6);


#endif

}
