
#ifndef MCAL_EXT_INTERRUPT_CFG_H_
#define MCAL_EXT_INTERRUPT_CFG_H_

#define GLOBAL_ENTERRUPT_STATUS ENABLE_GLOBAL_INTERRUPT

#define EXT_INT0_STATUS  EXTERNAL_INT0_RISING_EDGE

#define EXT_INT1_STATUS  EXTERNAL_INT0_RISING_EDGE

#define EXT_INT2_STATUS  EXTERNAL_INT0_RISING_EDGE


#endif /* MCAL_EXT_INTERRUPT_CFG_H_ */
