
#include "EXT_INTERRUPT_cfg.h"
#include "REGISTERS_ADDRESSES.h"
#include "../MACROS.h"

#ifndef MCAL_EXT_INTERRUPT_H_
#define MCAL_EXT_INTERRUPT_H_

#define ENABLE_GLOBAL_INTERRUPT 1
#define DISABLE_GLOBAL_INTERRUPT 0

#define EXTERNAL_INTERRUPT_0 6
#define EXTERNAL_INTERRUPT_1 7
#define EXTERNAL_INTERRUPT_2 5

#define EXTERNAL_INT0_LOW_LEVEL    0
#define EXTERNAL_INT0_ANY_CHANGE   1
#define EXTERNAL_INT0_RISING_EDGE  2
#define EXTERNAL_INT0_FALLING_EDGE 3

#define EXTERNAL_INT1_LOW_LEVEL    0
#define EXTERNAL_INT1_ANY_CHANGE   1
#define EXTERNAL_INT1_RISING_EDGE  2
#define EXTERNAL_INT1_FALLING_EDGE 3

#define EXTERNAL_INT2_RISING_EDGE  0
#define EXTERNAL_INT2_FALLING_EDGE 1

void INTERRUPT_ENABLE();

void EXT_INT0_INIT();

void EXT_INT1_INIT();

void EXT_INT2_INIT();



#endif /* MCAL_EXT_INTERRUPT_H_ */
